# Generated by Django 5.2 on 2025-04-22 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=200)),
                ("telefono", models.CharField(max_length=15)),
                ("correo", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Zapato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referencia", models.CharField(max_length=20)),
                (
                    "modelo",
                    models.CharField(
                        choices=[
                            ("Apache", "Apache"),
                            ("Apolo", "Apolo"),
                            ("Amaka", "Amaka"),
                            ("Nautico", "Nautico"),
                            ("Bota", "Bota"),
                            ("Casual", "Casual"),
                            ("Sport", "Sport"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "talla",
                    models.CharField(
                        choices=[
                            ("34", "34"),
                            ("35", "35"),
                            ("36", "36"),
                            ("37", "37"),
                            ("38", "38"),
                            ("39", "39"),
                            ("40", "40"),
                            ("41", "41"),
                            ("42", "42"),
                            ("43", "43"),
                            ("44", "44"),
                            ("45", "45"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("H", "Hombre"), ("M", "Mujer")], max_length=1
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("Rojo", "Rojo"),
                            ("Azul", "Azul"),
                            ("Verde", "Verde"),
                            ("Amarillo", "Amarillo"),
                        ],
                        max_length=10,
                    ),
                ),
                ("requerimientos", models.TextField()),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, default="Sin observaciones", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_terminacion", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("P", "Pendiente"),
                            ("C", "Completada"),
                            ("A", "Anulada"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, default="Sin observaciones", null=True
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.cliente"
                    ),
                ),
                (
                    "zapato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.zapato"
                    ),
                ),
            ],
        ),
    ]
