# Generated by Django 5.2 on 2025-05-03 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('talla', models.IntegerField()),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('color_principal', models.CharField(max_length=45)),
                ('categoria', models.CharField(max_length=45)),
                ('cantidad_disponible', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('idOrden', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_terminacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zapato',
            fields=[
                ('idZapato', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('talla', models.IntegerField()),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('color_principal', models.CharField(max_length=45)),
                ('categoria', models.CharField(max_length=45)),
                ('observaciones', models.CharField(blank=True, max_length=100)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('imagen_zapato', models.ImageField(blank=True, upload_to='pedidos/')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.orden')),
                ('zapato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.zapato')),
            ],
        ),
    ]
