# Generated by Django 5.1.6 on 2025-05-04 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_bodega_orden_zapato_detallepedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zapato',
            name='bodega',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='zapato',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='empleado',
        ),
        migrations.DeleteModel(
            name='Bodega',
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.DeleteModel(
            name='Zapato',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
    ]
