# Generated by Django 5.2 on 2025-05-12 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0005_zapato_estado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="zapato",
        ),
        migrations.AddField(
            model_name="pedido",
            name="empleado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="zapato",
            name="pedido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.pedido",
            ),
        ),
    ]
