# Generated by Django 5.2 on 2025-05-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0006_remove_pedido_zapato_pedido_empleado_zapato_pedido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
