# Generated by Django 5.2 on 2025-05-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0007_alter_cliente_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pendiente"),
                    ("Completada", "Completada"),
                    ("Anulada", "Anulada"),
                ],
                default="P",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="zapato",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendientes", "Pendiente"),
                    ("Producción", "En Producción"),
                    ("Anulado", "Anulado"),
                    ("Completado", "Completado"),
                    ("Entregado", "Entregado"),
                    ("Bodega", "En Bodega"),
                ],
                default="P",
                max_length=10,
            ),
        ),
    ]
