# Generated by Django 5.2 on 2025-05-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0008_alter_pedido_estado_alter_zapato_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pendiente"),
                    ("Completada", "Completada"),
                    ("Anulada", "Anulada"),
                ],
                default="Pendiente",
                max_length=10,
            ),
        ),
    ]
