# Generated by Django 5.2 on 2025-05-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0009_alter_pedido_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zapato",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendientes", "Pendiente"),
                    ("Producción", "En Producción"),
                    ("Anulado", "Anulado"),
                    ("Completado", "Completado"),
                    ("Entregado", "Entregado"),
                    ("Bodega", "En Bodega"),
                ],
                default="Pendiente",
                max_length=10,
            ),
        ),
    ]
